export const actions = {
  FETCH_WEATHER: 'FETCH_WEATHER',
  FETCH_WEATHER_ERROR: 'FETCH_WEATHER_ERROR',
  FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
  INITIALIZE_APPLICATION: 'INITIALIZE_APPLICATION',
  SIGNIN: 'SIGNIN',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
};