export const actions = {
  FETCH_CURRENT_WEATHER: 'FETCH_CURRENT_WEATHER',
  FETCH_CURRENT_WEATHER_ERROR: 'FETCH_CURRENT_WEATHER_ERROR',
  FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
  FETCH_FORECAST_WEATHER: 'FETCH_FORECAST_WEATHER',
  FETCH_FORECAST_WEATHER_ERROR: 'FETCH_FORECAST_WEATHER_ERROR',
  FETCH_FORECAST_WEATHER_SUCCESS: 'FETCH_FORECAST_WEATHER_SUCCESS',
  INITIALIZE_APPLICATION: 'INITIALIZE_APPLICATION',
  SIGNIN: 'SIGNIN',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SHOW_WEATHER_DETAILS: 'SHOW_WEATHER_DETAILS',
  SHOW_WEATHER_DETAILS_SUCCESS: 'SHOW_WEATHER_DETAILS_SUCCESS',
  SHOW_WEATHER_DETAILS_ERROR: 'SHOW_WEATHER_DETAILS_ERROR',
  FETCH_USER_COORDINATES: 'FETCH_USER_COORDINATES'
};